import { useState } from 'react';
import { api, type InterpretResponse, type ProcessKey } from '../api';
import { Card, ErrorBox, Loading, ModeBadge, SeverityBadge } from '../components/ui';
import { pct } from '../format';

const EXAMPLES: { label: string; process: ProcessKey; text: string }[] = [
  {
    label: 'AP invoice handling (SAP)',
    process: 'P2P',
    text: `Suppliers email invoices to ap@company.om. Every morning Fatma downloads them and keys them into MIRO against the PO.
If the price doesn't match the PO, she parks the invoice and emails the buyer; we track these blocked invoices in an Excel sheet that is reviewed on Thursdays.
Invoices without a PO go to the department head for approval by email and are then posted with FB60.
Invoices above OMR 10,000 must also be approved by the finance manager.
Treasury runs the F110 payment proposal every Tuesday, the CFO releases it in the bank portal, and we send remittance advice manually.`,
  },
  {
    label: 'Collections (Oracle)',
    process: 'O2C',
    text: `Sales orders are entered in Oracle Order Management. The credit controller checks the customer's credit limit manually in a spreadsheet before releasing the order.
Invoices are generated by AutoInvoice overnight and emailed to customers as PDFs.
Every month the AR team exports the aging report to Excel and calls customers who are more than 30 days overdue.
When payments arrive, the AR clerk matches bank statement lines to invoices by hand in Receivables, which usually takes two days after month-end.`,
  },
  {
    label: 'Month-end journals',
    process: 'R2R',
    text: `During the first three working days, accountants prepare accrual journals in an Excel template and upload them with GL Upload.
The financial controller reviews the support by email and approves the journals in SAP.
Bank and intercompany reconciliations are done in Excel and signed off by the finance manager.
The consolidation is done in a separate workbook and the management pack is emailed to the CEO on working day 8.`,
  },
];

export function WorkflowStudio() {
  const [text, setText] = useState(EXAMPLES[0].text);
  const [process, setProcess] = useState<ProcessKey | ''>('P2P');
  const [result, setResult] = useState<InterpretResponse | null>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const run = async () => {
    setBusy(true);
    setError(null);
    try { setResult(await api<InterpretResponse>('/workflow/interpret', { body: { text, process: process || undefined } })); }
    catch (e) { setError((e as Error).message); }
    finally { setBusy(false); }
  };

  const wf = result?.workflow;
  return (
    <>
      <Card title="Describe how your team actually works" sub="Paste an SOP, meeting notes, an email thread or an interview transcript. The AI models it as a structured workflow mapped to SAP/Oracle, then compares it with what your ERP data shows.">
        <div className="chips" style={{ marginBottom: 10 }}>
          {EXAMPLES.map((ex) => <button key={ex.label} className="chip" onClick={() => { setText(ex.text); setProcess(ex.process); setResult(null); }}>{ex.label}</button>)}
        </div>
        <label className="small muted" htmlFor="wf-text">Workflow description</label>
        <textarea id="wf-text" value={text} onChange={(e) => setText(e.target.value)} rows={8} maxLength={20000} />
        <div className="row" style={{ marginTop: 10, justifyContent: 'space-between' }}>
          <label className="row small">Process
            <select value={process} onChange={(e) => setProcess(e.target.value as ProcessKey | '')} style={{ width: 'auto' }}>
              <option value="">Detect automatically</option>
              <option value="P2P">Procure-to-Pay</option>
              <option value="O2C">Order-to-Cash</option>
              <option value="R2R">Record-to-Report</option>
            </select>
          </label>
          <button className="btn primary" onClick={run} disabled={busy || text.trim().length < 20}>{busy ? 'Interpreting…' : '✦ Interpret workflow'}</button>
        </div>
      </Card>

      {error && <ErrorBox message={error} />}
      {busy && <Loading rows={2} />}
      {wf && result && (
        <>
          <Card title={wf.title} sub={wf.summary} actions={<><ModeBadge mode={result.mode} />{result.notice && <span className="small muted">{result.notice}</span>}</>}>
            <div className="steps">
              {wf.steps.map((s) => (
                <div key={s.order} className="step">
                  <div className="step-num">{s.order}</div>
                  <div className="grid" style={{ gap: 6 }}>
                    <div className="row" style={{ justifyContent: 'space-between' }}>
                      <strong>{s.name}</strong>
                      <div className="pill-list">
                        <span className="badge">{s.role}</span>
                        <span className="badge">{s.system}</span>
                        <span className="badge">{s.manual ? '✋ Manual' : '⚙ Automated'}</span>
                        <span className="badge" style={{ borderColor: s.mappedActivity === 'CUSTOM' ? 'var(--warning)' : undefined }}>{s.mappedActivity === 'CUSTOM' ? '⚠ Custom step' : `↦ ${s.mappedActivity}`}</span>
                      </div>
                    </div>
                    <div className="small muted">ERP: {s.erpTransaction}</div>
                    {s.controls.length > 0 && <div className="small"><strong>Controls:</strong> {s.controls.join('; ')}</div>}
                    {s.painPoints.length > 0 && <div className="small"><strong>Pain points:</strong> {s.painPoints.join('; ')}</div>}
                    <div className="small"><strong>Automation idea ({pct(Math.min(1, Math.max(0, s.automationPotential)))} potential):</strong> {s.automationIdea}</div>
                  </div>
                </div>
              ))}
            </div>
          </Card>

          <div className="grid grid-3">
            <Card title="Approvals">
              {wf.approvals.length ? (
                <ul className="small" style={{ paddingLeft: 18, margin: 0 }}>
                  {wf.approvals.map((a, i) => <li key={i}><strong>{a.approver}</strong> — {a.threshold}<div className="muted">{a.trigger}</div></li>)}
                </ul>
              ) : <div className="muted small">No approval steps described.</div>}
            </Card>
            <Card title="Risks">
              {wf.risks.length ? (
                <div className="grid" style={{ gap: 8 }}>
                  {wf.risks.map((r, i) => <div key={i} className="small"><SeverityBadge severity={r.severity} /> {r.risk}<div className="muted">Mitigation: {r.mitigation}</div></div>)}
                </div>
              ) : <div className="muted small">No specific risks identified.</div>}
            </Card>
            <Card title="Quick wins">
              {wf.quickWins.length ? <ul className="small" style={{ paddingLeft: 18, margin: 0 }}>{wf.quickWins.map((q) => <li key={q}>{q}</li>)}</ul> : <div className="muted small">None suggested.</div>}
            </Card>
          </div>

          {result.gap && (
            <Card title="Documented vs. actual" sub={`Compared with the ${result.gap.process} event log — only ${pct(result.gap.actualFitness)} of real cases follow the standard model`}>
              <div className="grid grid-3 small">
                <div><strong>Described but never seen in the ERP</strong>
                  <ul>{result.gap.documentedNotObserved.length ? result.gap.documentedNotObserved.map((a) => <li key={a}>{a}</li>) : <li className="muted">None</li>}</ul>
                </div>
                <div><strong>Happens in the ERP but not described</strong>
                  <ul>{result.gap.observedNotDocumented.length ? result.gap.observedNotDocumented.map((a) => <li key={a}>{a}</li>) : <li className="muted">None</li>}</ul>
                </div>
                <div><strong>Off-system / custom steps</strong>
                  <ul>{result.gap.customSteps.length ? result.gap.customSteps.map((a) => <li key={a}>{a}</li>) : <li className="muted">None</li>}</ul>
                </div>
              </div>
            </Card>
          )}
        </>
      )}
    </>
  );
}
